config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord      ## will be ActiveRecord::Base in older Rails versions
  validates :name, presence: true, length: { maximum: 200 }

  def required_field?(field)  ## pass field name
    presence_validators = validators(field, ActiveRecord::Validations::PresenceValidator)
    !presence_validators.empty?
  end

  def length_val(field, minmax)  ## pass field name and which value i.e. :name, :maximum)
    length_validators = validators(field, ActiveRecord::Validations::LengthValidator)
    return nil if length_validators.empty?
    length_validators.first.options[minmax]
  end

  private
  def validators(field, val_class)  ## pass field name and the validator class to check
    _validators[field].select do |e|
      e.is_a? val_class
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController    ## defining classes = CamelCase
  def home                                       ## defining methods = snake_case
    ## Nothing here!
  end

  def about
  end
  
  def help
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController  ## Again basing this on the master template
  before_action :set_todo, only: [:show, :edit, :update, :destroy]   ## find Todo items

  def show 
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save                                        ## if the save is successful
      flash[:notice] = 'Your To-Do item was successfully created!'  ## add msg to flash
      redirect_to todo_path(@todo)                       ## use prefix for todos#show
    else                                                 ## if the save is unsuccessful
      render 'new'                                       ## show same form if db refuses
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)           ## update DB entry
      flash[:notice] = 'Your To-Do item was successfully updated!'
      redirect_to todo_path(@todo)         ## redirect to show view if successful
    else
      render 'edit'                        ## show same form w/ errs if update unsuccessful
    end
  end

  def index
    @todos = Todo.all                           ## simply grab all of the Todo items
  end

  def destroy
    @todo.destroy                                       ## remove entry from DB as learned
    flash[:notice] = 'Successfully deleted To-Do item'  ## notify user
    redirect_to todos_path                              ## go back to the To-Do list
  end

  private                                                ## THIS CONTROLLER ONLY
    def todo_params
      params.require(:todo).permit(:name, :description)  ## whitelisting params fields
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <h5 class="center">ToDoList</h5>
      </div>
    </div>
    <div class="row">
      <div class="col s12 l6">
        <p>This text will appear across the whole row on a small screen, or half the row on a large screen!</p>
        <p>If you think that's cool, it will also use this logic to determine whether the next div lives beside or below this one!</p>
      </div>
      <div class="col s12 l4 offset-l2">
        <h6>Footer Navigation</h6>
        <ul>
          <li><%= link_to root_path do %><i class="material-icons inline">home</i>&nbsp; Home<% end %></li>
          <li><%= link_to about_path do %><i class="material-icons inline">info</i>&nbsp; About<% end %></li>
          <li><%= link_to todos_path do %><i class="material-icons inline">list</i>&nbsp; To-Do List<% end %></li>
          <li><%= link_to new_todo_path do %><i class="material-icons inline">create</i>&nbsp; New To-Do Item<% end %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Made with love by Not Another Script Kiddie
      <a class="right" href="https://empydoodle.blogspot.com/p/a-british-gentlemans-guide-to-ruby-on.html">Guide / Blog</a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |k, msg| %>
  <script>M.toast({html: "<i class='material-icons'>info</i> &nbsp; <%= msg.to_s %>"})</script>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="nav-dropdown" class="dropdown-content">
    <% Todo.all[0..4].each do |todo| %>
      <li><%= link_to "#{todo.id}: #{truncate(todo.name, length: 40)}", todo_path(todo) %></li>
      <li class="divider"></li>
    <% end %>
    <li><%= link_to todos_path do %><i class="material-icons">list</i><br />To-Do List<% end %></li>
    <li class="divider"></li>
    <li><%= link_to new_todo_path do %><i class="material-icons">create</i><br />New To-Do item<% end %></li>
  </ul>
  <ul id="mobile-nav" class="sidenav">
    <li><h3 class="center"> ToDoList </h3></li>
    <li><%= link_to root_path do %><i class="material-icons inline">home</i> Home<% end %></li>
    <li><%= link_to about_path do %><i class="material-icons inline">info</i> About<% end %></li>
    <li><%= link_to help_path do %><i class="material-icons inline">help</i> Help<% end %></li>
    <li><%= link_to todos_path do %><i class="material-icons inline">list</i> To-Do List<% end %></li>
    <li><%= link_to new_todo_path do %><i class="material-icons inline">create</i> New To-Do Item<% end %></li>
  </ul>
  <nav>
    <div class="nav-wrapper">
      <%= link_to root_path, class: 'brand-logo left' do %>&nbsp; ToDoList<% end %>
      <a class="sidenav-trigger right" data-target="mobile-nav" onclick="openSideNav();"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li>
          <%= link_to root_path do %>
            <i class="material-icons">home</i>
          <% end %>
        </li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <!-- Dropdown Trigger -->
        <li>
          <a class="dropdown-trigger" href="#!" data-target="nav-dropdown">
            To-Do Items <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <script>
    function openSideNav() {
      var instance = M.Sidenav.getInstance(document.querySelector('.sidenav'));
      instance.open();
    }
  </script>
</header>

app/views/layouts/_scripts.html.erb
<script>
  document.addEventListener('DOMContentLoaded', function() {
    M.AutoInit();
    M.CharacterCounter.init(document.querySelectorAll('[data-length]'));
    M.updateTextFields();
    Array.from(document.getElementsByClassName('field_with_errors')).forEach(fixErrorDiv);
  });

  if (document.readyState!='loading') {
    M.AutoInit();
    M.CharacterCounter.init(document.querySelectorAll('[data-length]'));
    M.updateTextFields();
  };

  function fixErrorDiv(elem) {
    if(elem.childElementCount === 0 || elem.firstElementChild.localName === 'label') {
      return;  // skip label divs or divs already done
    };
    var parElem = elem.parentElement;  // find the input-field div
    var elems = Array.from(parElem.children).map(extractErrDivContent).flat();  // grab everything in it
    parElem.classList.add('field_with_errors');  // add required class to input-field div
    parElem.replaceChildren();  // remove everything in input-field div
    for (let i in elems) { parElem.append(elems[i]) };  // put everything in the new div
  };

  function extractErrDivContent(errDiv) {
    if(errDiv.className === 'field_with_errors') {
      return Array.from(errDiv.children);  // extract contents of field_with_errors div
    } else {
      return errDiv
    };
  };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%=
        [
          (yield(:html_title) if content_for?(:html_title)),
          params[:action].capitalize,
          'ToDoList'
        ].compact.join(' | ')
      %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>          <!-- don't have to include _ prefix here -->
    <%= render 'layouts/messages' %>           <!-- no need to specify file type either! -->
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <h2 class="header">This is the About page</h2>
  </div>
  <div class="row">
    <p>Build your own ToDoList web application using EmpyDoodle's questionable advice!</p>
    <p>Now with Materialize styling goodness!</p>
    <p>
      <%= link_to 'Source', 'https://github.com/EmpyDoodle/udemy_complete-ror-dev_alpha-blog/tree/materialize', target: '_blank' %>
    </p>
  </div>
</div>

app/views/pages/help.html.erb
<div align="center">
  <h2> Help </h2>
  <div> <p> No help for you. </p> </div>
</div>

app/views/pages/home.html.erb
<div align="center">
  <h2> Welcome to ToDoList </h2>
  <h3> Where all your Tos become Doed </h3>
</div>

app/views/todos/_button_destroy.html.erb
<%= link_to todo_path(@todo),
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: 'btn-floating btn-large waves-effect red tooltipped center',
            :"data-tooltip" => 'Delete To-Do Item',
            :"data-position" => (tooltip_pos rescue 'bottom') do %>
  <i class="material-icons">delete</i>
<% end %>

app/views/todos/_button_edit.html.erb
<%= link_to edit_todo_path(@todo),
            class: 'btn-floating btn-large waves-effect orange tooltipped center',
            :"data-tooltip" => 'Edit To-Do Item',
            :"data-position" => (tooltip_pos rescue 'bottom') do %>
  <i class="material-icons">create</i>
<% end %>

app/views/todos/_button_index.html.erb
<%= link_to todos_path,
            class: 'btn-floating btn-large waves-effect green tooltipped center',
            :"data-tooltip" => 'Back to To-Do List',
            :"data-position" => (tooltip_pos rescue 'bottom') do %>
  <i class="material-icons">subdirectory_arrow_left</i>
<% end %>

app/views/todos/_button_new.html.erb
<%= link_to new_todo_path,
            class: 'btn-floating btn-large waves-effect waves-light tooltipped',
            :"data-tooltip" => 'New To-Do Item',
            :"data-position" => (tooltip_pos rescue 'bottom') do %>
  <i class="material-icons">add</i>
<% end %>

app/views/todos/_button_show.html.erb
<%= link_to todo_path(@todo),
            class: 'btn-floating btn-large waves-effect blue tooltipped center',
            :"data-tooltip" => 'Back to To-Do Item',
            :"data-position" => 'bottom' do %>
  <i class="material-icons">visibility</i>
<% end %>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <div class="row">
    <div class="col s12 m8 xl5">         <!-- reduce the size on larger screens -->
      <div class="card red lighten-4">   <!-- add a colour to the class to fill it (default is white) -->
        <div class="card-content">
          <i class="material-icons medium right">error</i>
          <span class="card-title">To-Do item could not be saved</span>
          <p>
            <ul class="browser-default">
              <% @todo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= form_with model: @todo do |td_form| %>    <!-- using '=' erb tag as we're inserting -->

  <div class="row">
    <div class="input-field col s12 m8">
      <i class="material-icons prefix">title</i>
      <%= td_form.text_field :name,
                             class: 'validate',
                             required: @todo.required_field?(:name),
                             :"aria-required" => @todo.required_field?(:name),
                             :"data-length" => @todo.length_val(:name, :maximum) %>
      <%= td_form.label      :name %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 m8">
      <i class="material-icons prefix">subject</i>
      <%= td_form.text_area :description,
                            class: 'materialize-textarea validate',
                             required: @todo.required_field?(:description),
                             :"aria-required" => @todo.required_field?(:description),
                            :"data-length" => @todo.length_val(:description, :maximum) %>
      <%= td_form.label     :description %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m8 center-align">
      <%= td_form.button :class => 'btn waves-effect waves-light' do %>  <!-- use btn-large for bigger button -->
        <%= td_form.send(:submit_default_value) %>  <!-- Fetch what submit helper would have shown -->
        <i class="material-icons right">save</i>
      <% end %>
    </div>
  </div>

<% end %>  <!-- end the Rails form block -->

app/views/todos/edit.html.erb
<div class="container">
  <div class="row">
    <h3>Edit item: <strong><%= @todo.id.to_s %></strong></h3>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
  <div class="row">
    <div class="col s4 m2 xl1 offset-m1 offset-xl2 center">
      <%= render 'button_show' %>
    </div>
    <div class="col s4 m2 center">
      <%= render 'button_destroy' %>
    </div>
    <div class="col s4 m2 xl1 center">
      <%= render 'button_index' %>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class="container">
  <div class="row valign-wrapper">
    <div class="col s12 m8">
      <h3 class="header">Your To-Do List</h3>
    </div>
    <div class="col m4 hide-on-small-only">
      <%= link_to 'New To-Do Item', new_todo_path, class: 'btn waves-effect waves-light right' %>
    </div>
    <div class="fixed-action-btn hide-on-med-and-up">
      <%= render 'button_new', tooltip_pos: 'left' %>
    </div>
  </div>
  <div class="row">
    <table class="highlight">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th class="hide-on-small-only">Description</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @todos.each do |todo| %>
          <tr>
            <td><%= todo.id.to_s %></td>
            <td><%= link_to todo.name, todo_path(todo) %></td>
            <td class="hide-on-small-only"><%= truncate(todo.description, length: 100) %></td>
            <td>
              <%= link_to todo_path(todo),
                          :class => 'tooltipped',
                          :"data-tooltip" => 'Show To-Do Item',
                          :"data-position" => 'bottom' do %>
                <i class="material-icons">visibility</i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_todo_path(todo),
                          :class => 'tooltipped',
                          :"data-tooltip" => 'Edit To-Do Item',
                          :"data-position" => 'bottom' do %>
                <i class="material-icons">edit</i>
              <% end %>
            </td>
            <td>
              <%=
                link_to todo_path(todo),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        :class => 'tooltipped',
                        :"data-tooltip" => 'Delete To-Do Item',
                        :"data-position" => 'bottom' do %>
                <i class="material-icons">delete</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
  <div class="row">
    <h3>New To-Do item</h3>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
  <div class="row">
    <div class="col s12 m8 center-align">
      <%= link_to todos_path,
                     class: 'btn-floating btn-large waves-effect waves-light red tooltipped',
                     :"data-tooltip" => 'Cancel',
                     :"data-position" => 'bottom' do %>
        <i class="material-icons">close</i>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<% content_for(:html_title) { @todo.name } %>
<div class="container">
  <div class="row">
    <h3 class="header">To-Do item: <%= @todo.id.to_s %></h3>
  </div>
  <div class="row">
    <div class="col s12 m8">
      <ul class="collection">
        <li class="collection-item avatar">
          <i class="material-icons circle">title</i>
          <span class="title"><strong>Name</strong></span>
          <p><%= @todo.name.to_s %></p>
        </li>
        <li class="collection-item avatar">
          <i class="material-icons circle">subject</i>
          <span class="title"><strong>Description</strong></span>
          <p><%= @todo.description.to_s %></p>
        </li>
      </ul>
    </div>
  </div>
  <div class="row hide-on-med-and-down">
    <div class="col s4 m2 xl1 offset-m1 offset-xl2 center">
      <%= render 'button_edit' %>
    </div>
    <div class="col s4 m2 center">
      <%= render 'button_destroy' %>
    </div>
    <div class="col s4 m2 xl1 center">
      <%= render 'button_index' %>
    </div>
  </div>
  <div class="fixed-action-btn hide-on-large-only">
    <a class="btn-floating btn-large waves-effect">
      <i class="material-icons">more_vert</i>
    </a>
    <ul>
      <li><%= render 'button_edit',   tooltip_pos: 'left' %></li>
      <li><%= render 'button_destroy', tooltip_pos: 'left' %></li>
      <li><%= render 'button_index',  tooltip_pos: 'left' %></li>
    </ul>
  </div>
</div> 